config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :projects
  resources :cvs

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects, as: :source
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  def index
    @admin = User.first
  end


  private

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.create(project_params)
    @project.source_id = 1
    @project.source_type = "User"
    @project.save

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(user_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :detail)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @user = User.find_by_category("admin")
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:category, :name, :phone, :email, :blog_url, :github_url, :edu_info, :introduction, :skills)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cvs/index.html.erb
<div id="clip">
	<div id="intro-page"
		data-0="top: 0;"
		data-1000="top:0;"
		data-1200="top: -20px;"
		data-1300="top: -50px;"
		data-1500="top: -200px;"
		data-1700="top: -500px;"
		data-1900="top: -900px;"
		data-2100="top: -1400px;"
		data-2300="top: -10000px;" >
		<div class="logo-cell">
			<span class="logo skrollable rendered"
				data--10="top:10px;"
				data-600="top:32px;" >
				<%=image_tag("airscrew.png") %>
			</span>
		</div>
		<div class="tringle-bar"
			data--10="top:-190px;"
			data-350="top:-150px;"
			data-1000="top: -150px;"
			data-1500="top: -200px;" >
			<%=image_tag("tringle-top.png") %>
		</div>
		<div class="plane"
			data-300="top: -10px; transform[bounce]:scale(0.4); opacity: 1; display: block;"
			data-1000="top:1000px;transform[bounce]:scale(1.5); opacity: 1; display: block;"
			data-1300="top:1000px;transform[bounce]:scale(1.5); opacity: 0; display: none;">
			<%=image_tag("air-top.svg") %>
			<span class="airscrew"></span>
		</div>
		<div class="tringle-back">
			<%=image_tag("tringle-top.svg") %>
		</div>
		<div class="self-box"
			data-0="top: 0px; "
			data-400="top: -60px;">
			<div class="self-cnt"
				data-0="top: 300px; opacity: 1;"
				data-400="top: 400px; opacity: 0.6;"
				data-1200="top: 420px; opacity: 0;">
				<div class="cnt-bg"></div>
				<div class="photo-box">
					<%=image_tag("logo-self.png", class: "photo") %>
				</div>
				<div class="who-am-i">
					<h2><%= @admin.name %></h2>
					<h3>正在起飞的前端工程师</h3>
					<p>
						<a href="mailto:<%= @admin.email%>" class="strang email">EMAIL</a>
					</p>
				</div>
			</div>
			<div class="road-box">
				<div class="road-line"
					data-140="top: 0px;"
					data-2000="top: -4000px;"></div>
			</div>
			<%=image_tag("tringle-large-top.png", class: "bottom") %>

		</div>
		<div class="about-me"
			data-300="top: -800px;"
			data-1000="top: -50px;"
			data-1100="top: -50px;"
			data-1200="top: -70px;"
			data-1300="top: -100px;"
			data-1500="top: -200px;"
			data-1700="top: -300px;"
			data-1800="top: -400px;">
			<ul>
				<li><span>姓名&nbsp;|&nbsp;</span><%= @admin.name %></li>
				<li><span>手机&nbsp;|&nbsp;</span><%= @admin.phone %></li>
				<li><span>邮箱&nbsp;|&nbsp;</span><a href="mailto:<%= @admin.email%>"><%= @admin.email%></a></li>
				<li><span>博客&nbsp;|&nbsp;</span><a href="<%= @admin.blog_url %>">欢迎猛击</a></li>
				<li><span>教育背景&nbsp;|&nbsp;</span><%= @admin.edu_info %></li>
				<% if false %>
				<li><span>GitHub&nbsp;|&nbsp;</span><a href="<%= @admin.github_url%>">欢迎猛击</a></li>
				<% end %>
			</ul>
			<div class="introduction">
				<p>今夏最适合出境游的目的地是哪？当然是欧洲！
				受欧洲政经形势和国际市场多重因素的影响，欧元对人民币的汇率跌破7.0大关，创下了欧元诞生以来的历史最低；同时，很多国家大使馆也进一步放宽了旅游签证的条件。钱不是问题，签证也不是问题，还有比这个时候更适合去欧洲的吗？
				无论你是向往西方文明的印迹，或是只想吃吃吃买买买；无论你是早已去过那些耳熟能详热门景点的旅行达人，或只是一个蠢蠢欲动的出境游小白，都可以试试下面这几个欧洲小众目的地。
				</p>
			</div>
			<div class="star star-top-left">
				<%= image_tag("star.png") %>
			</div>
			<div class="star star-top-right">
				<%= image_tag("star.png") %>
			</div>
			<div class="star star-bottom-left">
				<%= image_tag("star.png") %>
			</div>
			<div class="star star-bottom-right">
				<%= image_tag("star.png") %>
			</div>
			<%=image_tag("about-me-bottom.png", class: "bottom") %>
		</div>
		<div class="clouds-bar">
			<div class="cloud-1"
				data-0="left: 150px;"
				data-1500="left: 350px;"
				data-3000="left: 150px" >
				<%= image_tag("cloud-1.svg", height: 171 )%>
			</div>
			<div class="cloud-2"
				data-0="right: 50px;"
				data-1500="right: 350px;"
				data-3000="right: 50px"
				>
				<%= image_tag("cloud-2.svg", height: 171 )%>
			</div>
		</div>
	</div>
	<div id="skills-page"
		data-1300="top:200px; left: 0px;"
		data-1780="top: 0px; left: 0px;">
		<div class="plane-2"
			data-1780="top: 50px; left: -200px;"
			data-2000="top: 300px; left: 300px;"
			data-2500="top: 10px; left: 800px;" >
			<%= image_tag("air-2.svg") %>
			<span class="airscrew-2"></span>
		</div>
		<div id="skills"
			data-0="left: 0;"
			data-1900="left: 0px;"
			data-3000="left: -1960px;" >
			<div class="skill-cloud-bar skill-1" >
				<div class="skill-cloud-1"></div>
				<div class="skill-info">
					<strong>HTML/CSS</strong>
					<ul class="detail-list fade">
						<li>能够编写结构合理的页面布局；</li>
						<li>能使用CSS3达到更加的页面效果；</li>
						<li>了解HTML5新语义化标签和新特性；</li>
						<li>能够使用Bootstrap、jQueryUI等前端开发框架；</li>
						<li>熟悉Chrome开发工具辅助开发。</li>
					</ul>
				</div>
				<div class="cover-cloud"></div>

			</div>
			<div class="skill-cloud-bar skill-2">
				<div class="skill-cloud-2"></div>
				<div class="skill-info">
					<strong>JavaScript</strong>
					<ul class="detail-list fade">
						<li>掌握原生JavaScript,能使用其编写一般项目；</li>
						<li>了解面对对象的程序设计；</li>
						<li>能运用Ajax开发；</li>
						<li>能运用jQurey框架辅助开发。</li>
					</ul>
				</div>
				<div class="cover-cloud"></div>
			</div>
			<div class="skill-cloud-bar skill-3">
				<div class="skill-cloud-3"></div>
				<div class="skill-info">
					<strong>ROR框架</strong>
					<ul class="detail-list">
						<li>了解Ruby on Rails框架，能编写简单需求；</li>
						<li>理解MVC架构；</li>
						<li>能配合后端进行数据交换。</li>
					</ul>
				</div>
				<div class="cover-cloud"></div>
				<div class="detail"></div>
			</div>
			<div class="skill-cloud-bar skill-4">
				<div class="skill-cloud-4"></div>
				<div class="skill-info">
					<strong>开发工具</strong>
					<ul class="detail-list">
						<li>能使用Git等版本控制工具；</li>
						<li>能在Linux环境下进行开发；</li>
						<li>能使用Photoshop进行简单的图片处理，根据页面结构进行合理的图片分割；</li>
					</ul>
				</div>
				<div class="cover-cloud"></div>
				<div class="detail"></div>
			</div>
		</div>
		<div id="projects"
			data-1900="left: 1960px;"
			data-3000="left: 0px;" >

		</div>
	</div>
</div>
<script>

	var scrollObj = skrollr.init({
		  smoothScrolling: true,
		  smoothScrollingDuration: 1000,

	});
	var $email = $('.email');
	$email.on("mouseenter", function(){
		$email.fadeOut("slow","swing",function(){
			$email.text("yundong.me@gmail.com");
			$email.fadeIn("slow","swing");
		});
	});
	$email.on("mouseout", function(){
		$email.fadeOut("slow","swing",function(){
			$email.text("EMAIL");
			$email.fadeIn("slow","swing");
		});
	});

	var html = new skill(".skill-1 .skill-info",  ".skill-cloud-1",  {height: "70px", time: 1500});

	var js = new skill(".skill-2 .skill-info", ".skill-cloud-2",  {height: "60px", time: 1500});

	var ror = new skill(".skill-3 .skill-info",  ".skill-cloud-3",  {height: "40px", time: 1500});

	var tools = new skill(".skill-4 .skill-info", ".skill-cloud-4",  {height: "60px", time: 1500});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_field :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Projects</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% @projects each do |project| %>
	<h3>project.title</h3>
	<p>project.detail</p>
<% end %>

app/views/projects/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :blog_url %><br>
    <%= f.text_field :blog_url %>
  </div>
  <div class="field">
    <%= f.label :github_url %><br>
    <%= f.text_field :github_url %>
  </div>
  <div class="field">
    <%= f.label :edu_info %><br>
    <%= f.text_field :edu_info %>
  </div>
  <div class="field">
    <%= f.label :introduction %><br>
    <%= f.text_area :introduction %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_field :skills %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render "public/header" %>
<div id="container">
	<div class="content">
		<h1>Editing User</h1>
		<%= render 'form' %>
		<%= link_to 'Back', users_path %>
	</div>
</div>
<%= render "public/side" %>

app/views/users/index.html.erb
<%= render "public/header" %>
<div id="container">
        <div class="content">
                <h1>Listing Users</h1>
                <ul>
                        <li> Type<%= @user.category %></li>
                        <li>Name<%= @user.name %></li>
                        <li>Phone<%= @user.phone %></li>
                        <li>Email<%= @user.email %></li>
                        <li>Blog<%= @user.blog_url %></li>
                        <li>Github<%= @user.github_url %></li>
                        <li>Edu<%= @user.edu_info %></li>
                        <li>Intro<%= @user.introduction %></li>
                        <li>Skills<%= @user.skills %></li>
                        <li><%= link_to 'Edit', edit_user_path(@user) %></li>
                </ul>
        </div>
</div>
<%= render "public/side" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @user.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Blog url:</strong>
  <%= @user.blog_url %>
</p>

<p>
  <strong>Github url:</strong>
  <%= @user.github_url %>
</p>

<p>
  <strong>Edu info:</strong>
  <%= @user.edu_info %>
</p>

<p>
  <strong>Introduction:</strong>
  <%= @user.introduction %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @user.skills %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>